---
title: "qPCR Plots"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(tidyverse)
```

# U76553 qPCR

```{r U76553.read_data}
U76553.qpcr_data <- read.delim("data/U76553_qpcr_results.tsv")
```

```{r U76553.plot, message = FALSE}
ggplot(U76553.qpcr_data, aes(x = log_qty, y = ct)) + 
  geom_point(color = 'blue', size = 0.5) +
  theme_light() + 
  geom_smooth(method = 'lm', color = 'black', size = 0.1,
              linetype = 'dashed') + 
  scale_x_continuous(breaks = seq(2, 10, 2), expand = c(0, 0), limits = c(0, 10)) +
  scale_y_continuous(breaks = seq(5, 35, 5), expand = c(0, 0), limits = c(0, 35)) + 
  labs(x = "Log Concentration (gene copies/reaction)",
       y = "Cycle Threshold",
       title = "Standard curve of U76553") + 
  theme(panel.grid.minor = element_blank() ) + 
  annotate("text", x = 2, y = 20, label = "atop(y == -3.8806 * x + 40.705, R^2 == 0.996)", parse = TRUE) +
  theme(panel.border = element_rect(color = "black", fill = NA, size = 2),
        plot.title = element_text(hjust = 0.5))
  
```

# EF175099 qPCR

```{r, EF175099.read_data}
EF175099.qpcr_data <- read.delim("data/EF175099_qpcr_results.tsv")
```

```{r EF175099.plot, message = FALSE}
ggplot(EF175099.qpcr_data, aes(x = log_qty, y = ct)) + 
  geom_point(color = 'blue', size = 0.75) +
  theme_light() + 
  geom_smooth(method = 'lm', color = 'black', size = 0.1,
              linetype = 'dashed') + 
  scale_x_continuous(breaks = seq(2, 10, 2), expand = c(0, 0), limits = c(0, 10)) +
  scale_y_continuous(breaks = seq(5, 35, 5), expand = c(0, 0), limits = c(0, 35)) + 
  labs(x = "Log Concentration (gene copies/reaction)",
       y = "Cycle Threshold",
       title = "Standard curve of EF175099") + 
  theme(panel.grid.minor = element_blank() ) + 
  annotate("text", x = 2, y = 20, label = "atop(y == -3.7974 * x + 40.518, R^2 == 0.9988)", parse = TRUE) +
  theme(panel.border = element_rect(color = "black", fill = NA, size = 2),
        plot.title = element_text(hjust = 0.5))
  
```
